version: "3.9"
services:
  db:
    container_name: quest-db
    image: postgres:13.3
    ports:
      - "5432:5432"
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=game
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  web:
    container_name: quest
    build: .
    image: quest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy